[package]
name = "nvim-cat"
version = "0.1.0"
authors = ["Cheney Lin <lincheney@gmail.com>"]

[dependencies]
serde = "~ 0.8"
rmp = "~ 0.7"
rmp-serde = "0.10"
libc = "~ 0.2"
term_size = "~ 0.2"

[dependencies.clap]
version = "~ 2.19"
features = ["wrap_help"]
default-features = false
